

- name: setup beanstalkd config
  template:
    src: "CentOS-{{ ansible_distribution_major_version }}-beanstalkd"
    backup: yes
    dest: /etc/sysconfig/beanstalkd
    group: root
    owner: root
    mode: 0644
  when: custom_config_src is not defined

- name: setup custom beanstalkd config
  copy:
    src: "{{ custom_config_src }}"
    backup: yes
    dest: /etc/sysconfig/beanstalkd
    group: root
    owner: root
    mode: 0644
  when: custom_config_src is defined
